### ISSUE TITLE
How to download files from backblaze using the current package?

### ISSUE THREAD

**Issue by PhilipeRLeal** [WardPearce/aiob2#2]
Dear developers,

Despite my efforts, the current python's package does not seem to allow an easy download API from BackBlaze.

Would it be possible to insert some examples in your [webpage](https://backblaze.readthedocs.io/en/latest/examples.html#uploading-a-file) so to facilitate this package usage?

Sincerely

**Comment by WardPearce** [comment]
Morning,
The documentation for downloading can be seen [here](https://backblaze.readthedocs.io/en/latest/api.html#backblaze.bucket.awaiting.file.AwaitingFile.download).

I agree that it should be included in the examples page, thanks for the issue!

**Comment by WardPearce** [comment]
Thanks for the issue, I've added it to the documentation [here](https://backblaze.readthedocs.io/en/latest/examples.html#downloading).

**Comment by PhilipeRLeal** [comment]
Thank you for the update.

It is now much clearer how to download the data.

Regarding a related question, how can one check (create a list) of all
files within a given Bucket?

Would there be a direct way in which your package could retrieve that
information?

Sincerely,

Philipe Riskalla Leal,
Sensoriamento Remoto - INPE


Em qua., 3 de mar. de 2021 às 18:28, Ward <notifications@github.com>
escreveu:

**Comment by WardPearce** [comment]
https://backblaze.readthedocs.io/en/latest/api.html#backblaze.bucket.awaiting.AwaitingBucket.file_names

This documents how to list files.
