### ISSUE TITLE
upload 200M mp4file raise httpx.ReadTimeout

### ISSUE THREAD

**Issue by kof0012** [WardPearce/aiob2#3]
upload 200M mp4file 
raise httpx.ReadTimeout
how can i deal with it?
Thanks!

**Comment by WardPearce** [comment]
Hey, thanks for supporting the project!
You can change the read timeout [here](https://backblaze.readthedocs.io/en/latest/api.html#base).

e.g.
```py
client = backblaze.Awaiting(
    key_id="...",
    key="...",
    timeout=300
)
```
