### ISSUE TITLE
Error in accessing files from bucket

### ISSUE THREAD

**Issue by PhilipeRLeal** [WardPearce/aiob2#4]
Dear developers,

Given the actual release of this Backblaze (branch master) package, there are some small typos in the bucket/blocking/__init__.py module.

The errors are in the "file_versions" and "file_names" methods.

Instead of using NextFilename as an attribute of the file object, one must use "fileName"; also, the "nextFileId" returns a typeError.

Sincerely,

**Comment by WardPearce** [comment]
Dope, thanks for the PR! I haven't touched this repo for a bit. I'll clean up the source code a little tonight & add a workflow for packing to pypi.

Have a nice day.
