### ISSUE TITLE
Problems in deleting a AwaitingFile from bucket

### ISSUE THREAD

**Issue by PhilipeRLeal** [WardPearce/aiob2#6]
Dear developers,

I have noticed that it is not so easy to delete a given bucket's file (a.k.a., an AwaitingFile object) from BackBlaze.

It seems that the AwaitingFile does not have a filename as an attribute that could be easily assessed for invoking its inherent "delete" method.

Therefore, if possible, I believe that the method "delete" from the AwaitingFile object could be reformulated in such a way that no "filename" is required from the user. This parameter should be directly accessible as an attribute of the class' instance. After all, it is of common understanding that the file to be deleted is itself, and not some other file; thus, no name should be required for its own deletion from Backblaze.

Let me know your thoughts.

sincerely,

**Comment by WardPearce** [comment]
Hey,
The issue is that b2 requires both a file ID & a file name to delete it. I could make the name parameter in delete optional & if not given it will call self.get to grab the file name for that ID.

**Comment by WardPearce** [comment]
https://github.com/WardPearce/backblaze/commit/1de00a6c95995036b9943f644e8cf8f83bd97994
Added this in the latest commit

**Comment by WardPearce** [comment]
`0.0.8` has now been packed to pypi with your PR, some minor syntax fixes & optional delete parameter.

**Comment by PhilipeRLeal** [comment]
Dear WardPearce,

thank you for the effort. I believe that the package is now much more complete and concise.

Later on, I will check the changes provided.

Sincerely,
